### ISSUE TITLE
Po rozklikunti zobrazovat fotku, nie logo

### ISSUE THREAD

**Issue by mukrop** [zverinec/ks-muni-web#14]
Zatial kludne placeholder fotku, ale ma to byt iny objekt ako logo. (Graficke spracovanie Ada este doda.)
Zaroven to vyriesi problem s tym, ze aktivity s logom otvaraju box, ktory je prilis velky.

Plus fotka by mala byt rovnaky link ako je link na akciu.

**Comment by malinajan** [comment]
Tohle se už na úrovni vytvářecího skriptu děje, jen je ta fotka a logo teď prostě stejný obrázek.

**Comment by mukrop** [comment]
Ok, vyberiem pokusne nejake fotky. Kam a s akym nazvom to nahravat?

**Comment by malinajan** [comment]
`id_photo.any_suffix` do složky `web-data`.
