### ISSUE TITLE
Podporovat pre akcie viacero kategorii

### ISSUE THREAD

**Issue by mukrop** [zverinec/ks-muni-web#16]
Napriklad seminare z biochemie by sa mali zobrazovat aj pod chemiou aj pod biologiou (podobne intersob, N-trophy a dalsie medzioborove akcie).
Vymysliet, aku syntax v tabulke na to chces (oddelovane ciarkou? bodkociarkou? medzerou?)

**Comment by malinajan** [comment]
Tohle to umí. Stačí do *obor* zadat víc věcí oddělených čárkou. Např. *biologie, informatika*.

**Comment by mukrop** [comment]
Ok, pridam do tabulky.

**Comment by mukrop** [comment]
Done.
