### ISSUE TITLE
Ako oznacujeme, ktora aktivita je "seminar"?

### ISSUE THREAD

**Issue by mukrop** [zverinec/ks-muni-web#17]
Navrhujem tomu urobit samostatny stlpec s priznakom do tabulky.

**Comment by malinajan** [comment]
Momentálně je na to konfigurací v souboru `src/config.py`. Přemýšlel jsem, jestli to dát do tabulky a nakonec jsem se rozhodl, že tato informace je jen technikálie webu a že je to hodně platformně závislé (třeba v brožuře žádné takové dělení [zatím] není). Proto lokální konfigurák jen pro web a ne sloupec v tabulce.

Je tu ale mnoho zásadnějších otázek spojených s tím, co ne/psát do tabulky:
 * Jak získat cestu k logu? Políčko v tabulce? Nebo pevné jméno `id_aktivity_logo.abc`.
 * Podobně pro fotku aktivity.
 * Jak snchronizovat data v gDrive s webem? Stáhnout jedno csv ručně není problém, ale stahovat celý adresář s logy? Neudělat radši nějaké přímé napojení třeba na `make download`?
 * Chceme umět měnit pořadí aktivit? Pokud ano, jen konfigurákem pro web, nebo globálně v tabulce (použitelné i pro sazby jinam než na web)? Jak pořadí zaznamenávat?
 * Chceme zobrazovat plný text aktivity, nebo jen zkratku? Uvádět tuto informaci do tabulky nebo do konfiguráku?

**Comment by mukrop** [comment]
Tiez som nad tym rozmyslal.
* Loga mi pridu praktickejsie sytemom `id_aktivity.abc`. Team drive nepodporuje zdielanie adresarov, pripadny automaticky download by teda musel linkovat vsetky subory po jednom a podla mna by bolo prilis neprehladne drzat vsetky odkazy aktualny (ked si to porovnam so zlozkou, kde vsetky aktualne loga vidim).
* Fotka aktivity podobne. Tj. mat 2 adresare (fotky, loga) a tam vzdy `id.abc`.
* Osobne mi stiahnut 2 adresare a jedno csv pride OK. Nejaky `make download` by bol pohodlnejsi, ale v kombinacii s gDrive to asi nedame. Alebo ta napada, ako by to bolo pohodlne pre obidve strany?
* Poradie aktivit urcite chceme vediet ovplyvnovat. Podla mna radsej poradim v tabulke. Sadzba brozury bude pravdepodobne ctit toto poradie (seminar prvy), ale ta bude aj tak rucne.
* Plny nazov vs. skratka: Asi by som navrhol prerobit tabulku tak, ze tam bdue stlpec "nazov", ktory sa bude preberat na web a bude primarny a potom druhy typu "poznamka k nazvu", kde bude priapdne doplnujuce info (BRKOS bude mat v nazve skratku, ale Android pre stredoskolakov bude mat kod v poznamke). Co myslis?
* A presne preto, ze vacsinu veci mame v tej gTabulke mam sklony povedat, ze tam radsej budem mat servisny stlpec seminar ano/nie, ako tuto jedinu vec musiet upravovat niekde inde. V tej tabulke ten stlpec moze byt skryty (tak ako potom asi skryjem aj ID, to je tiez celkom technicka informacia).

**Comment by malinajan** [comment]
Bude na to skrytý sloupec v tabulce.

**Comment by malinajan** [comment]
@mukrop Vytvoříš v tabulce ten sloupec, nebo to mám udělat já?

**Comment by mukrop** [comment]
Urob si ho sam tak, aby ti vyhoovala syntax.

**Comment by malinajan** [comment]
Done.
