### ISSUE TITLE
Domena?

### ISSUE THREAD

**Issue by mukrop** [zverinec/ks-muni-web#18]
Davam na rozmyslanie: Na ako domenu cielime?
* ks.muni.cz aktualne smeruje na uciteucit.cz (ale zlym sposobom, nesedi certifikat)
* ks.* je podla mna blbost (nejde len o korespondencne seminare)
* vzhladom na medzifakultnost by som cielil priamo pod domenu muni.cz
* asi najlepsie, co som zatial vymyslel je prostredoskolaky.muni.cz

Nejake napady?

**Comment by mukrop** [comment]
Bude to prostredoskolaky.muni.cz. Zariadim.

**Comment by malinajan** [comment]
Škoda, že nás nenapadlo nic lepšího. Doména mi přijde docela dlouhá. Snad máš pravdu v tom, že si lidi nepamatují URL... :/. Rád se nechám dát do kopie při zařizování, zajímalo by mě, co doména 3. řádu na MUNI obnáší.

**Comment by mukrop** [comment]
Do kopie som ta bohuzial dat nemohol, ide to cez ticketing system. Obnasa to toto: https://it.muni.cz/sluzby/registrace-domen (par veci z toho nesplname, takze este ocakavam trochu vyjednavania).

**Comment by malinajan** [comment]
Ty věci o redakčním systému radši ani nechci číst... :/ Za mě je preferovaný CNAME na *marsyas*.

**Comment by mukrop** [comment]
Skoro urcite to bude od nich tvrda poziadavka, ze to musi bezat u nich (nieco podobne uz som pred tym riesil). Predpokladam, ze dostaneme konto a priestor na webserver.ics.muni.cz.

**Comment by malinajan** [comment]
Ok, tomu nerozumím. Pokud tam budu mít přístup přes ssh a budu moct dělat git pull, asi se s tím dá žít. Ideálně aby fungoval automatický deploy...

Počkáme, co na nás vymyslí.

**Comment by mukrop** [comment]
Predpokladam, ze CNAME budeme mat v priebehu tohto tyzdna, Prosim nezabudni prestavit Google Analytics, dat Stourimu vediet, ze sme tam pridali web a dopisat ho do tabulky zdrojov.

**Comment by malinajan** [comment]
Hotovo.
