### ISSUE TITLE
Web analytika?

### ISSUE THREAD

**Issue by mukrop** [zverinec/ks-muni-web#19]
Navrhujem nahodit Google Analytics, aspon na uvodny rok, aby sme mali prehlad, kolko ludi tam tak chodi.

Chcelo by to spolocny ucet. U mna existuje uz davnejsie nie uplne pouzivany ucet pod Organizaciou Spolek pratel severske zvere -- je tam len nas youtube kanal. V tabulke vidim, ze KSI pouziva GAnalytics.

Mohli by sme KSI GAnalytics ucet (account) premenovat na spolkovy a prehodit pod neho ten youtube (property) a ten moj zmazat?

**Comment by malinajan** [comment]
ACK, zkusím se na ten účet podívat.

**Comment by malinajan** [comment]
KSI GAnalytics jsou ve skutečnosti Heňovy GAnalytics. KSI s Googlem nemá celkem nic moc společného. Moc nevím, pod jaký účet bych to měl převést. Spolek nějakou organizaci na Googlu nebo něco takového nemá, ne? Jde na Googlu vůbec něco takového zařídit?

**Comment by mukrop** [comment]
Premigrovane od Hena pod organizaciu Zverinca. Mas tam administratorsky pristup. Vytvoril som novy tracking code pre tuto stranku, najdes to tam.

**Comment by malinajan** [comment]
Ok.
