### ISSUE TITLE
Paticka

### ISSUE THREAD

**Issue by mukrop** [zverinec/ks-muni-web#20]
Paticku by som narhol nasledovne:
* V ciernom podklade pisat stredne sedym textom, nech je to menej vyrazne ako teraz.
* Do lava zarovnany napis "(c) Masarykova univerzita, <aktualny rok>" (dolava znamena tam, kde zacina prvy blok)
* Do prava zarovnany napis "posledni zmena: <datum posledneho spustenia build skriptu>" (doprava znamena tam, kde konci posledny blok)

**Comment by malinajan** [comment]
Poslední změna jako čas buildu webu nebo čas posledního commitu? Po najetí bych jako hint určitě zobrazoval commit id.

**Comment by mukrop** [comment]
Obidvoje dava logiku. Asi by som dal cas buildu a do tooltipu commit (to tam bduu tie casy nepriamo obidva).

**Comment by mukrop** [comment]
* Navrhujem z datumu poslednej upravy vyhodit cas (ten pre navstevnikov uz nie je relevanyny podla mna).
* Tooltip identifikujuci commit sa nakoniec nerealizova?

**Comment by malinajan** [comment]
Tooltip se nerealzoval, protože ziskání id commitu zpomalovalo build.
