### ISSUE TITLE
Text dole

### ISSUE THREAD

**Issue by mukrop** [zverinec/ks-muni-web#21]
Issue na diskusiu, co vsetko ma byt v texte dole. Prvy nastrel:
* Kratky odstavec, co to je (nieco take, ako je aktualne)
* Ze existuje aj brozura + link (vaham, ci toto nedat vyraznejsie -- dot vpravo maly obrazok brozury, ktory bude tiez klikatelny?)
* Info, kto stranky spravuje (napisal by som, ze to ma aktualne v sprave Spolek pratel severske zvere FI MU). Sucasne by z toho malo byt jasne, ze ked nieco nie je spravne, kam sa ozvat.
* Info o tom, ze je to dielo nas troch (design, spracovanie dat a technicka realizacia: Ada Miklikova, Honza Horacek a Martin Ukrop)

Napada vam este nieco?

**Comment by malinajan** [comment]
Link na tabulku, aby si lidi nemuseli pamatovat dlouhou google adresu, ale jen klikli na odkaz na webu?

**Comment by mukrop** [comment]
Som za, kludne tam ten link pridaj.

**Comment by malinajan** [comment]
Chceme dolů ještě něco? Nebo změnit formulace? Nebo zavíráme issue?

**Comment by mukrop** [comment]
Vadi mi vela kratkych odstavcov. Navrhjem prve dva zlucit do jedneho odstavca a ostatne do druheho (resp. ak chces, posledny mozes nechat). Cast "Tabulka aktivit pro správce." by som upravil ako "Chcete-li zmenit, co se zobrazuje k vasi aktivite, upravte to v tabulce pro spravce."

**Comment by malinajan** [comment]
Takže zavíráme?

**Comment by mukrop** [comment]
Ano.
