### ISSUE TITLE
Odkazy na akce

### ISSUE THREAD

**Issue by malinajan** [zverinec/ks-muni-web#22]
@mukrop V současné době jsou v tabulce odkazy, které nejsou platné url (neobsahují protokol). Navrhuji tyto adresy přímo v tabulce přepsat na validní url (`http://`, `https://`) místo implemeentace nějakých chtristik do skriptu, kterým se web generuje.

**Comment by mukrop** [comment]
Ano.

**Comment by mukrop** [comment]
Upravil som. Casom to ale asi bude chciet dalsi stlpec "display URL" -- link, ktory dame do brozury. Tam sa protokol nehodi, naopak chces, aby to bolo co najstrucnejsie.
