### ISSUE TITLE
activities.csv veřejné

### ISSUE THREAD

**Issue by malinajan** [zverinec/ks-muni-web#23]
@mukrop Dotaz: je ok mít soubor `activities.csv`, který je svg export, jako součást veřejného repozitáře?

Teď to tak je a to zejména z toho důvodu, aby stačilo udělat `git pull && make` a web se vytvořil.

**Comment by mukrop** [comment]
Tiez som nad tym vahal. Nie je tam nic tajne, ale toto repo je vygooglitelne. Trochu sa mi nepaci predstava, ze ked budes googlit mena ludi (pripadne aktivit), tak skoncis tu. Je to taky trochu iracionalny pocit. 

Takto to ma ale okrem tebou spominanej vyhody aj tu, ze to drzi historiu verzii textov o aktivitach (co je v gDocs slabsie).

Tebe sa to zda uplne OK, alebo si vahal?

**Comment by malinajan** [comment]
Váhal jsem, nemám jasný názor, proto se ptám.

Pokud budeme realizovat něco jako `make update` pro stažení aktuálních fotek a celé tabulky z gDrive, je tato tabulka vážným kandidátem na odstranění z repozitáře. Na druhou stranu, teď máš jistotu, že se ti web vyrobí vždycky stejně a ne zrovna podle toho, jak se kdo naposled uklikl v tabulce.

**Comment by malinajan** [comment]
(Klidně bych tyto koncepční otázky pořešil osobně, podle mě to bude efektivnější než si psát tady.)

**Comment by malinajan** [comment]
Btw. Když jsou v tabulce prakticky veřejná data, tak je za tebe ok, kdyby byla google složka veřejně k dispozici pro čtení? Znamenalo by to značné zjednodušení automatického updatu dat pro web z gDrive.

**Comment by mukrop** [comment]
Verejne na citanie podla mna ano, ale iba "Shared with the link", aby nebola vygooglitelna. Ale ked nat tym tak premyslam, asi ju budes chciet mat hard-coded v Makefile, takze google ju aj tak naindexuje...
Inak mat csv v repe a nebyt na pospas ukliknutiam v tabulke sa mi paci.

**Comment by malinajan** [comment]
Bude private repo.
