### ISSUE TITLE
Ake vsetky aktivity tam chceme?

### ISSUE THREAD

**Issue by mukrop** [zverinec/ks-muni-web#25]
Pri revizii odkazov som dospel k tomu, ze budeme musiet stanovit, ake aktivity tam chceme a ake nie.  Niektore su za mna velki kandidati na vyhodenie, napriklad "Další akce z oboru chemie (podle domluvy)'. 

Je tam viacero kategorii na zvazenie. Osobne by som tam nedaval akcie pre verejnost (Botanické exkurze pro veřejnost), ale iba veci, ktore su pre stredoskolakov, zakladoskolakov alebo ucitelov strednych/zakladnych skol (a to tie druhe 2 kategorie su na diskusiu). Aktivity v spolupraci s univerzitou mi nevadia (fyzikalny tabor prirodoveda+UDIF, chemicke sustredenie kampus+Luzanky).

Ked vyladime predstavu o webe, prejdeme to asi osobne pripad po pripade.

**Comment by malinajan** [comment]
Aktivity na spodu se nebudou deployovat.

**Comment by malinajan** [comment]
Nedeplyují se aktivity, které nemají zadané id. Jestli chceš, klidně si je v tabulce popřehazuj, nebo je je nech na místě a id dej buď prázdné nebo `-`. Issue necháváme otevřené?

**Comment by mukrop** [comment]
Nemusis. Na triedenie este pride, staci mi vediet, ze nemaju mat ID. Poriadok si tam uz nejako urobim.
