### ISSUE TITLE
Jak zobrazovat obory, které nemají žádné semináře?

### ISSUE THREAD

**Issue by malinajan** [zverinec/ks-muni-web#28]

**Comment by mukrop** [comment]
Dat im kolonku "Ostatni" reps. "Jine"?

**Comment by malinajan** [comment]
Spíš mi přijde, že možná nechceme zobrazovat rozdělení na 2 sekce aktivit. Nevím.

**Comment by malinajan** [comment]
To chce pokecat s Áďou.
