### ISSUE TITLE
Prvy user testing (Domca)

### ISSUE THREAD

**Issue by mukrop** [zverinec/ks-muni-web#32]
Domci som nechal klikat webom, postrehy nizsie.
* Myslienka aj prevedenie sa jej paci.
* Zasadny problem: Vobec neprisla na to, ze na akcie sa da klikat a nieco viac sa tam bude zobrazovat. Ocakavala, ze po kliku ju to prehodi priamo na stranku seminara. Riesenie: Dat na spodok bloku sipku dole, ktora sa pripadne pre prechode mysou bude zvyraznovat. Skratka aby tam bolo nieco, co naznacuje, ze sa to ta este "otvorit".
* Tlacitko "vice info" v hlavicke je divne, vyhodila by ho uplne (asi suhlasim).
* Rozdelenie na vlajkove akce a dalsie akcie jej prislo divne. "Dalsi akce" su dost nevyrazne, ked rozklikla chemiu, hore bol Vibuch a myslela si, ze "dalsi akce" su jednoducho dalsie, nie nutne chemicke. Navyse po rozkliku jednotlivych kategorii je na vrchu vacsinou len jedna akcia, co nevyzera uplne dobre a trochu to navodzje pocit, ze to je jedina. Uprednostnovaniu velkych seminarov rozumie (a suhlasi). Navrh riesenia: Mat vsetko spolu (nerozdelovat vlajkove/dalsi) ale na zaciatku mat zaradene tie vlajkove (predsa len, ludia prirodzene klikaju z lava doprava, zhora dole). Randomizacia akcii pripadne v ramci tychto dvoch kategorii (ale bez viditelneho oddelenia).
* Texty na otvaracich blokoch su casto prilis dlhe, vobec sa jej to nechcelo citat. Navrhuje cca 2.5-3 riadky v aktualnej velkosti. Ako urobit, aby tam nebolo prilis vela volneho miesta? Moj navrh narychlo bolo dat pismo 130% a dat mu margin cca 15-20px, vyzeralo to tak relativne dobre. V sadzbe na 3 stlpce zostava pismo take velke, ako je teraz (ci sa zabezpeci, ze zabera menej miesta a nerobi miesto pod obrazkom).
* Zlta je oproti pozadiu malo kontrastna, nevidno ju. Ked ide cez tlacitka oborov, myslela si, ze sipka proste mizne. Podobne po zakliknuti oboru to stlacene tlacitko velmi nevidno. Moze to byt mojim monitorom, ale zase tak netradicnu konfiguraciu nemam, treba s tym pocitat. Navrh je zvolit inu zvyraznovaciu farbu (mozno nejaky iny odtien modrej z hlavicky?).
* Nejake drobne vylepsenia paticky, tie som rovno zapracoval.

**Comment by AdelaRozari** [comment]
DOMCA: 
2. bod >>> zkusím to nějak vyřešit, pobavím se s lidma jak to udělat, šipečka "jako na rozrolování" je fajn nápad.
3. bod >>> já to více info bych stále chtěla. 
4.bod >>> o tom se budeme muset asi pobavit víc
5.bod >>> Texty jsou dlouhé, souhlasím. To jsem zatím neřešila právěže jsem nevěděli kolik textu bude.
6.bod >>> Nechat žlutou, za tím si stojím. Při zakliknutí změnit barvu písma na modrou?

**Comment by malinajan** [comment]
Rozděleno na separátní issues.
