### ISSUE TITLE
Název menu "Obory" při malé šířce webu

### ISSUE THREAD

**Issue by malinajan** [zverinec/ks-muni-web#39]
Odstranit, refaktorovat, ...?

**Comment by malinajan** [comment]
Spojit název s rozbalovacími čárkami, vycentrovat, po rozbalení jen texty, je grafika.

**Comment by mukrop** [comment]
Ocakavaj, ze este pribudne "Geografie" (alebo sa geologie a geografie zluci, ale potom asi nemame lepsi nazov ako "vedy o zemi").

**Comment by malinajan** [comment]
Přijde mi, že předělávat menu je hodně práce na to, jaký je z toho užitek. Jak moc to chceme?

**Comment by mukrop** [comment]
Netrvam na tom.
Ale aktualne mi pride, ze ten napis "Obory" celkom zavadzia -- ked rozbalujem menu, tak to je len v stlpci, ktory je vlavo zuzeny napisom "Obory" a vpravo rozbalovacim tlacitkom. Takze na riadku je aj v mobilovej sirke len jeden obor, aj ked realne by sa zmestili 2.
Ak by sme dokazali dat napis "Obory" a rozbalovaci tlacitko _nad_ rozbaleny zoznam (ktory by mal teda k dispozicii plnu sirku stranky a boli by vedla seba 2 obory), podla mna by to situaciu dost zlepsilo (to, co mne najviac vadi je prave ten uzky stlpec, ked su vsetky obory nad sebou).

**Comment by malinajan** [comment]
Souhlasím, to by snad nějak jednoduše šlo. Kouknu na to.
