### ISSUE TITLE
Issue tracking

### ISSUE THREAD

**Issue by malinajan** [zverinec/ks-muni-web#40]
Co používat jako primární komunikační kanál na komunikaci a issue tracking? Áďa má ráda Trello. Honzovi se líbí zavírání issue přes commity.

**Comment by mukrop** [comment]
Na vyjasnenie: Martinovi je to jedno, ale jemne NEpreferuje Trello (aj ked tam si tiez viem nastavit notifikacie na mail a potom mi to bude uplne jedno).

**Comment by malinajan** [comment]
Primárně github.
