### ISSUE TITLE
Privátní repo

### ISSUE THREAD

**Issue by malinajan** [zverinec/ks-muni-web#41]
Make this repo private.

**Comment by mukrop** [comment]
Nejaky postup?
Pytal som sa na nazor ostatnych, asi nevidia az taky extra problem v tom, aby to bolo aj verejne.
(Side note: Z pohladu GDPR staci veci riesit tak, ako ich riesime aktualne -- aspon zatial.)

**Comment by malinajan** [comment]
Žádný postup, doposud to pro mě nebyla priorita. Vážně to teda chceme privátní? (Pokud aktivity vědí, že je tabulka veřejná a jsou s tím ok, jsem pro veřejné repo.)

**Comment by mukrop** [comment]
Stale o tom nie som 100% presvedceny, ze to potrebujeme (vid nasa minula diskusia osobne). Asi som aj v pohode s tym, ze to nechame verejne.

**Comment by malinajan** [comment]
Bude veřejné. Alespoň se můj budoucí zaměstnavatel může podívat na můj úžasný skript v Pythonu <3 (a hlavně mám zelené čtverečky na GH profil :P).

**Comment by mukrop** [comment]
Zelene stvorceky by si myslim mohol mat aj tak -- daj sa myslim zaradit do statistik aj aktivita z privatnych repozitarov.
