### ISSUE TITLE
Rozbalovací šipka na spodu aktivity

### ISSUE THREAD

**Issue by malinajan** [zverinec/ks-muni-web#43]

**Comment by mukrop** [comment]
Je to celkom fajn. Zvazujem este nejaky hover na tie bloky. Navyse teraz tie modre sipky podla mna prilis svietia a biju sa s tymi logami.

Co takto sipky sede a modre len na hover? (@AdelaRozari)

**Comment by malinajan** [comment]
>
>
>
Jsem pro. Prosim o zaslani rgb kodu sede barvy. Staci hover pri hoveru na
sipku, nebo se ma sipka vybravit, kdyz najedu na blok aktivity?

**Comment by AdelaRozari** [comment]
šeda #C9C9C9 ?

**Comment by mukrop** [comment]
Urcite hover na cely blok (ak je to rozumne mozne). A ak to nie je extra vela prace, sipka modra, ked je aktivita rozkliknuta.

**Comment by AdelaRozari** [comment]
Šipky zacentrovat na střed (vždy pevně vespod) a udělat šedé, poslala jsem v mejlu :)
