### ISSUE TITLE
Kratší texty aktivit

### ISSUE THREAD

**Issue by malinajan** [zverinec/ks-muni-web#45]
@mukrop, zapracoval jsem velikost textu a marginy popisů aktivit podle domluvy na poradě. Teď je třeba upravit texty v tabulce. Uděláš to, nebo to budeme řešit nějak jinak?

**Comment by mukrop** [comment]
Prvu hrubu verziu prekratim ja, doladia si to potom aktivity sami.

**Comment by mukrop** [comment]
Done.
