### ISSUE TITLE
Scrollovanie po kliku "Vice info"

### ISSUE THREAD

**Issue by mukrop** [zverinec/ks-muni-web#46]
Drobnost (ktoru sme uz myslim aj spominali): Mohla by sa stranka po kliku na "vice info" _prescrollovat_ na tu sekciu namiesto odskoku? Aktualne mi to pride trochu matuce, lebo nevies, kam ta to hodilo.

**Comment by malinajan** [comment]
Znamená to přidat javascript, v prostém css postupné scrollování neudělám. Já jsem obecně spíš proti JS pokud není potřeba. Jak moc to plynulé scrollování chceme?

**Comment by mukrop** [comment]
Mne to pride, ze aktualne je to trochu zmatocne, lebo trochu neviem, kam ma to hodi, takze by mi to za ten JS mozno aj stalo. Ale je to subjektivny nazor. 
@AdelaRozari, co myslis?
