### ISSUE TITLE
Konzistentnost casovych udajov na kartach

### ISSUE THREAD

**Issue by mukrop** [zverinec/ks-muni-web#47]
Karty aktivit maju pod nazvom casovy udaj (říjen-duben, celoročně, neděle na začátku prosince, ...), ktore sa mi zdaju nekonzistentne. Bude je tam len cas roka, kedy sa to odohrava, alebo je v tom aj dlzka akcie (den, sobota, tyzden, ...). Moznosti, ktore vidim:
1. Dat tam len mesiac/cast roka, kedy to je.
2. Dat tam mesiac/cast roka aj dlzku (pozor, moze byt prilis dlhe).
3. Nechat to takto pomiesane ad-hoc (lebo pre niektore akcie to ma zmysel, pre ine nie).

Moj navrh je ist do 1. (ale zvazujem aj 2.). Aktualny ad-hoc stav sa mi velmi nepaci.
Co myslite @horacekj @AdelaRozari ?

**Comment by malinajan** [comment]
Jsem za 3). Osobně tohle issue nepovažuji za důležité.

**Comment by AdelaRozari** [comment]
Podle mne by bylo fajn něco jako: měsíc, celoročně. Datumy, soboty apd. ne.

**Comment by mukrop** [comment]
Done.
