### ISSUE TITLE
Chybajuci organizatori

### ISSUE THREAD

**Issue by mukrop** [zverinec/ks-muni-web#48]
Ked som skracoval popisy, tak som sa rozhodol vyhadzovat z textu veci typu "...organizovana ustavom XY fakulty ZW", lebo v kratkom popise zbytocne zaberali miesto a boli nudne. Ale tato informacia by tam niekde mohla byt.

Moj navrh je dat to sedou kurzivou do bloku po rozkliku (bud na vrch alebo na spodok), pretoze mi to pride ako dolezita informacia. Nie ani tak pre tych stredoskolakov, ako pre univerzitu samotnu a PR jednotlivych organizacii (napriklad ULeT by mal Instruktorov Brno a UDiF, zlepsili by sme tym meno ustavov, ktore nieco robia v porovnani s tymi, co nic nerobia, ...).

Nazory? @horacekj @AdelaRozari

**Comment by mukrop** [comment]
Plus organizatori by mohli byt rozkliknutelni (UDiF, IS Brno, ustavy, fakulty, spolky -- vsetci maju svoje weby a ak im to trochu zvisi PR, tak je to podla mna fajn odmena za to, ze usporiadavaju nieco pre stredoskolakov).

**Comment by malinajan** [comment]
Osobně považuji zmínku o organizátorech za zbytečnou. Tohle bych prostš nechal v režii akcí smaotných: buď si to dají na svůj web akce nebo ne.

**Comment by mukrop** [comment]
Pre stredoskolaka to skoro zbytocne je, ale buduje to PR a beriem to tak trochu ako sluzbu tym spolkom/ustavom/pracoviskam, ktore to robia. Ja by som to tam stale celkom chcel, takze este by som pockal na nazor @AdelaRozari.

**Comment by AdelaRozari** [comment]
Souhlasím naprosto s Martinem. Zakomponuju to do návrhu bloku po rozkliku. PR oborů je velmi důležitý a bude se to i lépe prezentovat na vyšších místech (jako PR web obecně).

**Comment by malinajan** [comment]
Prosimvás, a kde ta data o organizátorech vezmeme? Žádná data k tomu nemáme, na tož odkazy na web organizátorů. Někteří organizátoři ani web nemají... Pořád si stojím za tím, že tohle je blbost.

**Comment by mukrop** [comment]
Ja pocitam s tym, ze organizatora ku kazdej akcii v prvej varke dopisem (a pripadne si to v ramci kontrol opravia). Vacsina organizacii web ma, prevez casto je to ten web, ktory chcu davat ku akcii, co je podla mna blbost (napr. web ustavu botaniky a zoologie).

**Comment by mukrop** [comment]
@horacekj, v akom formate ti mozem do tabulky dopolnit tych organizatorov? Problem je v tom, ze jednotlive aktivity maju obcas aj viac organizatorov a chcel by som, aby ten nazov bol preklik na ich web. Napada mi nasledovne:
1) Vkladat do noveho stlpca pramo html markup s organizatormi a adkazmi -- nesystemove a krehke, ale jednoduche
2) vkladat do noveho stlpca ID organizatorov oddelenych ciarkami a v novom tabe vytvorit novu tabulku organizatorov v tvare ID, nazov, link (ktora sa bude stanovat ako samostatne csv a asi ju az tak casto aktualizovat nebude treba) -- systemovejsie, flexibilne, ale viac prace a vytvara to zlozitejsiu strukturu
3) Nejaky iny format, aky ta napadne.

**Comment by malinajan** [comment]
Uááá. Vůbec netuším, co z tohoto issue má vypadnout. Dokud mi Áďa neřekne, co na tom webu má být, těžok ti můžu říct,co potřebuju.

**Comment by mukrop** [comment]
Moja hruba predstava je takato:
![organizatori](https://user-images.githubusercontent.com/1871676/38422030-99265ae6-39a9-11e8-9b9d-be66cd8da663.png)

**Comment by mukrop** [comment]
Chceme to tam, fakulty to vymysleli nezavisle na tom, ze my sme to planovali. Aj s preklikom.
Tj. @AdelaRozari prosim o zahrnutie do navrhu a @horacekj prosim o specifikaciu, v akom formate to chces, aby som ti to mohol doplnit do tabulky.
Bude to 1-n (1-3?) organizatorov per akcia, kazdy sa bude dat rozkliknut. Moje navrhy vid vyssie.

**Comment by malinajan** [comment]
Než ti vymyslím specifikaci dat, tak potřebuju vědět **co** tam chceš. Chápu, že to asi bude klikací link. Bude vždy na web? Nebo někdy na e-mail? Budou tam organizátoři napsáni textem, ikonkou, nebo čím? To musí říct Áďa, až poté já můžu říct, co potřebujeme.

**Comment by mukrop** [comment]
Viz obrazok vyssie, preto som ho uz vtedy vytvaral. Urcite to budu texty (typicky nazvy ustavov na prirodovede, ktore nemaju nutne logo), urcite ten link bude klikaci a nebude to mail. Toto nemoze povedat Ada, lebo to vychadza z toho, ake data mame.

**Comment by malinajan** [comment]
Navrhuju formát dat něco jako:

```
Spolek přátek severské zvěře: http://zverinec.fi.muni.cz, FI MUNI: http://fi.muni.cz/
```

Vše to jednoho sloupce tabulky, data se budou duplikovat, ale to asi nevadí.

Striktně bych se držel oddělovací sekvence `, ` (čárka & mezera) a `: ` (dvojtečka & mezera), aby bylo možné umístit do názvů nebo url čárky a dvojtečky. `, ` a `: ` se v názvu organizátora a v url snad neobjeví. Co myslíš?

**Comment by malinajan** [comment]
(teď mě teda napadlo, že když v názvu bude čárka, tak asi hned za ní bude aky mezera, meh, chce to vymyslet něco lepšího) Nebo se v názvu čárka prostě nevyskytne?

**Comment by malinajan** [comment]
Navhuju středník. Středník v názvu ani v URL snad jisto jistě nebude.

```
Spolek přátek severské zvěře: http://zverinec.fi.muni.cz; FI MUNI: http://fi.muni.cz/
```

**Comment by mukrop** [comment]
Ok, bodkociarka (strednik) je fajn. Inak mi ten format pride rozumny. A suhlasim s tym, ze duplikacia informacii v tomto rozsahu mi nevadi. Doplnim ti to niekedy v najblizsej dobe.

**Comment by AdelaRozari** [comment]
viz vedle
