### ISSUE TITLE
Design bloku po rozkliku

### ISSUE THREAD

**Issue by mukrop** [zverinec/ks-muni-web#49]
Design bloku po rozkliku by to chcelo trochu vyladit. Pod textami je aktualne prilis vela miesta (texty predlzovat nechcem). Nepaci sa mi, ze tlacitko "web akcie" je niekedy vyssie, niekedy nizsie podla dlzky textu (radsej by som ho mal stabilne v rovnakej vyske).
@AdelaRozari, mohla by si sa prosim pozriet na design vo vsetkych 4 velkostiach obrazovky a vyladit medzery, velkost pisma, pozcovanie a pod? Bud urobit navrh, alebo sem Honzovi napisat, co zmenit (co zvacsit, zmensit a pod.). Podla vedlajsieho issue zvaz, ci do toho zaradit este nejake info (ja by som bol za organizujuce organizacie).

**Comment by AdelaRozari** [comment]
![image](https://user-images.githubusercontent.com/37794763/39421311-bb741f8a-4c68-11e8-861f-e9414fcaa085.png)

**Comment by AdelaRozari** [comment]
@mukrop @horacekj 
---Takhle si to představuju já. Rozkliknutelné odkazy (promo) organizátorů, šedá barva,  po najetí ztmavit (šedá) 
--- Odkaz na web vždy ukotvený dole, tak jak je navrhnuto. 
--- Velikost písma jsem dala 21, řádkování 30. Tloušťku nech jakou máš ty u té Cambrie.

**Comment by malinajan** [comment]
Ok, zapracuju.
