### ISSUE TITLE
Obrazok brozury do textu o stranke

### ISSUE THREAD

**Issue by mukrop** [zverinec/ks-muni-web#50]
Navhujem do textu o stranke (blok nad patickou) vlozit obrazok brozury, aby ludia zistili, ze aj ta existuje (pripadne si stiahli pdf). Moj navrh je zarovnanie vpravo pod poslednym stlpcom (sirka 1 stlpca), zobrazuje sa bud len vo verzii 4 stlpce, alebo aj v verzii pre 3 (podla toho, ako to bude vyzerat). Vo verzii 2 a 1 stlpec to bude vyzerat tak, ako teraz.

![brozura-2017](https://user-images.githubusercontent.com/1871676/38166886-9e2e8be4-352b-11e8-9b7b-7caa716c9f6e.jpg)

**Comment by malinajan** [comment]
Cheme tam skutečně dávat tuhle brožuru? Já jsem myslel, že brožura odkazovaná nebude, dokud nebude nová, která se bude trochu podobat designu webu, takže ji možná budeme chtít zasadit nějak specificky.

**Comment by mukrop** [comment]
Tato je stale aktualna a zda sa mi zbytocne cakat na novu. Ano, ked bude nova, tak obrazok a link vymenime, ale dovtedy je podla mna tato OK. A PDF s brozurou by som si tiez hostoval lokalne (na stabilitu URL webov FI ani PrF sa podla mna uplne neda spolahnut).

**Comment by malinajan** [comment]
No podle mě ta fotka brožury nebude vypadat hezky... Probereme asi někdy osobně, nebo to tam zkusím dát a uvidíme.

> A PDF s brozurou by som si tiez hostoval lokalne (na stabilitu URL webov FI ani PrF sa podla mna uplne neda spolahnut).

Určitě.

**Comment by mukrop** [comment]
Potreboval by som to vidiet (ano, stale je tam sanca, ze to bude proste vyzerat zle). Ale trochu to pritiahne citatelov k "nudnej textovej casti" a navyse to vyriesi vizualny problem s tym, ze ten text je kratky na sirokych monitoroch.
Navrhol by som dat to tam a potom diskutovat podla toho, ako to bude vyzerat (ak to nie je vela prace).

**Comment by AdelaRozari** [comment]
Za mne vyzkoušet.

**Comment by mukrop** [comment]
Upravil som velkost podla mojich povodnych predstav.
![text](https://user-images.githubusercontent.com/1871676/38172685-26f6a0e4-35b1-11e8-9508-90cab74878bd.png)

**Comment by AdelaRozari** [comment]
I like it!

**Comment by malinajan** [comment]
@AdelaRozari No a teď kterou verzi? Tu, která je současně na webu, nebo tu Martinovu?

**Comment by mukrop** [comment]
Mne sucasna pride prilis mala, tak som ju potiahol aj cez blok nadpisu (hoci beriem, ze je to nesystemove).

**Comment by AdelaRozari** [comment]
martinovu. Tedy tu větší.

**Comment by malinajan** [comment]
Tohle zase nevypadá úplně hezky na menší šířce :(
![screenshot_20180401_173606](https://user-images.githubusercontent.com/12673442/38174806-50b7a604-35d3-11e8-8940-5f3f8068707e.png)

**Comment by malinajan** [comment]
Tak jsem to udělal tak, že se obrázek na malé šířce dá až pod nadpis, koukněte na současný web, jestli se vám to líbí.

**Comment by mukrop** [comment]
Kombinacia vedla nadpisu pri velkom a pod nadpisom pri mensom je super!
Aktualne tam je este bug, ze 1-2 stlpce tam nie je ten nadpis "O akcich".

BTW. nema ten nadpis byt skor "O tomto webu" Alebo "Akce MUNI" alebo nieco take? Divajuc sa na aktualny obsah, ten nie je uplne o akciach...
