### ISSUE TITLE
Akce pre ucitelov?

### ISSUE THREAD

**Issue by mukrop** [zverinec/ks-muni-web#51]
A @AdelaRozari sme sa na konci este rozpravali, co s akciami pre ucitelov. Zhodli sme sa, ze ich nechceme miesat do akcii pre stredoskolakov, ale do brozury ich urcite chceme. Na web sme zvazovali ich bud nedat, alebo urobit tretiu sekciu "Akce pro ucitele" (tak ako su vlajkove a dalsi). Ak by ich casom bolo vela (co nevidim, ako pravdepodobne), tak by sa zvazil samostatny sestersky web s podobnym designom.

@horacekj, co si myslis?
(Akcie pre ucitelov sa na webe aktualne nezobrazuju, su 3-4.)

**Comment by malinajan** [comment]
Navrhuju akce nerobrazovat.

**Comment by mukrop** [comment]
OK, s tymto riesenim sme s Adelou asi zatial v pohode. Ak by sa ich niekto extra dozadoval, rozoberieme t v buducnosti znova.
