### ISSUE TITLE
Řazení akcí po rozkliku oboru

### ISSUE THREAD

**Issue by AdelaRozari** [zverinec/ks-muni-web#52]
Našla jsem bug - po rozkliku oboru se vlajková akce hodí na konec.

**Comment by malinajan** [comment]
Akce se po rozkliku oboru řadí náhodně, protože ponechání vlajkových akcí na začátku je implementačně trochu náročnější. Takže určitě chceme ty vlajkové akce vepředu, jo?

**Comment by AdelaRozari** [comment]
Když jsem klikla na matematiku, brkos byl uplně poslední. Tak určitě ne. Vlajkové akce 100% na začátek.

**Comment by malinajan** [comment]
ok, dám vlajkové ake na začátek

**Comment by mukrop** [comment]
Suhlas, vlajkove akcie na zaciatok su dolezite. Ak by to neslo, tak radsej ozeliem to nahodne radenie, len aby boli vlajkove na zaciatku.
