### ISSUE TITLE
Více info

### ISSUE THREAD

**Issue by AdelaRozari** [zverinec/ks-muni-web#53]
Více info po kliknutí nedělá nic. Určitě se nesescroluje stránka dolů na info.

**Comment by mukrop** [comment]
U mna to funguje (Chrome).

**Comment by AdelaRozari** [comment]
u mně už taky. Zapřísahám se, že to nešlo. (i po refreši)

**Comment by malinajan** [comment]
(@AdelaRozari má pravdu, byl tam bug, který jsem před chvílí opravil :) )
