### ISSUE TITLE
Ikony

### ISSUE THREAD

**Issue by AdelaRozari** [zverinec/ks-muni-web#54]
Poslala jsem vám ikony co bych chtěla místo prázdných míst. Kdyby vás napadlo jaký motiv chybí, pište :) 
Napadá mne:
--- Netopejři?

**Comment by malinajan** [comment]
Máme asi 20 placeholder ikon napříč různými obory. Jak je chceme přiřazovat aktivitám?

Vidím 2 možnosti:
 * každé aktivitě podle jejího oboru vyberu náhodou z ikon pro obor, při rebuildu stránky se zvolí jiná náhodná
 * každá aktivita bude mít pevnou, v tom případě navrhuji Ádiny ikonky nahrát přímo do Google Drivu.

@AdelaRozari @mukrop ?

**Comment by mukrop** [comment]
Podla mna bude mat kazdka obrazok fixne (vyberieme taky, ktory sa bude hodit). Poctam s tym, ze to povyberam, a ak mi bude nieco chybat, napisem.

**Comment by AdelaRozari** [comment]
Každé aktivitě fixně ikonu. Některé aktivity budou mít stejné. Přesvědčila jsem sama sebe, že to nebude tak strašné, protože za a) my nemůžeme za to, že nemají logo. B) nemám na to prostor.

**Comment by malinajan** [comment]
Mám teď chvíli čas, tak (alespoň některé) ikony přiřadím.

**Comment by malinajan** [comment]
@AdelaRozari Na "Embedded systems" prosím nějakou ikonku robota či něco takového. Embedded systems = mikrokontroléry, roboti, automatizace, logické obvody, ... (prostě hardware)

**Comment by AdelaRozari** [comment]
Oki. Zítra dodělám. Vypadá to dobře!

**Comment by AdelaRozari** [comment]
Čip je vytvořen.

**Comment by mukrop** [comment]
Honzo, aktualizujes to prosim?

**Comment by malinajan** [comment]
Jo, jdu na to...

**Comment by malinajan** [comment]
Rád bych otevřel ještě jednu otázku: co s "fotkama" u akcí, které nemají fotku? Tj. ten obrázek, který se zobrazuje v rozkliklém bloku akce. @AdelaRozari, @mukrop ?

**Comment by mukrop** [comment]
Na vacsinu si myslim, ze nam este nieco dodaju. Kde nie, dame ilustracny zaber (z inej akcie alebo tematicky z fakultnych archivov).

**Comment by mukrop** [comment]
Fotky budu z fakutlnych archivov, dohodnute so zodpovednymi osobami.
