### ISSUE TITLE
Zmena hlavneho titulku

### ISSUE THREAD

**Issue by mukrop** [zverinec/ks-muni-web#55]
Navrhujem zmenit titulok stranky na "_Prirodovedni_ akce na MUNI pro stredoskolaky".
Viem, ze je to dost slhe, ale je to do velkej miery politicke rozhodnutie -- zistil som, ze prirodoveda sa bude dost branit pridavaniu dalsich fakult. Ak to (aspon pre tuto sezonu) udrzime ako prirodovedne akcie, lahsie ziskame podporu prrodovedy, projekt bude o kus stabilnejsi a podla mna je vacsia sanca na ziskanie financovania. Do buducna sa osobne dalsim fakultam nebranim, ale na tento rok to fakt asi nechajme takto. Detaily vam porozpravam osobne, ak chcete.

**Comment by malinajan** [comment]
WTF is that?! Nadpis bude škaredý (dlouhý). Jsem na FI, jestli chceš, můžu se stavit.

**Comment by mukrop** [comment]
Bude skaredsi, ale podla mna to stoji za to. Ak sa chces zastavit, tak este budem tak FI tak pol hodku.

**Comment by mukrop** [comment]
![nadpis](https://user-images.githubusercontent.com/1871676/38422965-d104634c-39ac-11e8-804c-11d77f1843f8.png)

**Comment by mukrop** [comment]
Po dohode s fakultami nechat tak, ako je to teraz.
