### ISSUE TITLE
Uprava paticky (loga, info fotky)

### ISSUE THREAD

**Issue by mukrop** [zverinec/ks-muni-web#56]
Do paticky prosim doplnit loga PřF, FI, ESF (ak budu na rozne vyznamnych miestach, tak v tomto poradi).
(@AdelaRozari pripadne vymysli, ako to tam naskladat, aby to rozumne vyzeralo na monitore aj mobile. Podla vlastneho uvazenia kludne aj vyhod obalku brozury, ak myslis.)

Do posledneho odstavca doplnit vetu "Pouzite fotografie jsou z archivu jednotlivych akci a archivu PrF a FI."

**Comment by AdelaRozari** [comment]
@horacekj @mukrop Napadlo mne dát je pod to (v tvém pořadí vedle sebe) vycentrované na střed. Nejjednoduší řešení. a na mobilech nejmenší verze co jde s tím, že se budou zobrazovat jednotlivě pod sebou. ^^

**Comment by malinajan** [comment]
Mohla bys to prosím nějak upřesnit? Já úplně nechápu, jak by to mělo vypadat. Jakou mají mít loga barvu? Jakou barvu mají mít na hover?

**Comment by AdelaRozari** [comment]
@horacekj Vektorové loga - bílé? Ony mají být rozkliknutelné? :/

**Comment by malinajan** [comment]
No intuitivně bych čekal, že by měly být rozkliknutelné. Proč je dělat nerozkliknutelné? Takže chceš standardní kulatá loga fakult jako třeba v patičce https://kscuk.fi.muni.cz/?

**Comment by AdelaRozari** [comment]
@horacekj Ano, standartní kulatá. moc jiných možností není + nové logo MUNI. udělej je klidně rozkliknutelná tmavší šedou. (tak jak to prostě máre v patičce)

**Comment by malinajan** [comment]
Nové logo ještě není v oficiálním logotypu, používám zatím staré.

**Comment by malinajan** [comment]
Nakonec jsem to udělal vlastně stejně jako na K-SCUK webu. Uprostřed to nevypadalo moc hezky. Je to takto ok?

**Comment by AdelaRozari** [comment]
@horacekj Supr!
