### ISSUE TITLE
Vykaz (hodiny)

### ISSUE THREAD

**Issue by mukrop** [zverinec/ks-muni-web#57]
Prosim doplnte sem kolko mate aktualne hodin prace na tomto projekte. Idealne cim skor (tym skor bude stipko).

**Comment by malinajan** [comment]
Zatím 37 hodin. Za mě by bylo super 200-300 Kč / h.

**Comment by AdelaRozari** [comment]
já mám přes 40h. S hodinovkou 400 jsem uplně mimo :D
