### ISSUE TITLE
Doplnit licenci

### ISSUE THREAD

**Issue by malinajan** [zverinec/ks-muni-web#59]
@mukrop Chceme na web licenci? Něco jako

> Obsah je poskytován pod licencí CC BY-NC v4.0. © MU 2018. 

do patičky.

**Comment by mukrop** [comment]
Navrhujem:
> CC BY-NC v4.0 Masarykova univerzita

* Podla mna nemozes kombinovat CC a ©, to su 2 rozne licencie.
* Rok by som nedaval, bude to treba aktualizovat (raz rocne, ale aj tak sa to bude zabudat), navyse je datum poslednej zmeny vpravo.
* Nazov licencie musi byt link na text licencie (viz info na https://creativecommons.org/choose/) -- myslim, ze toto je nutna podmienka, aby bola ta licencia pravne v poriadku.

**Comment by malinajan** [comment]
Ok.

**Comment by mukrop** [comment]
Mohol by ten link na licenciu nebyt modry? Podla mna to takto vyzera dost zle. Nechal by som ho sedy ako zbytok napisu, len na hover by bol podciarknuty. (Je to preklik z legalnych dovodov, nevadi mi, ze viuzualne to nebude uplne jasne.) 
Nazor?

**Comment by malinajan** [comment]
Zkus refresh s vylitím cache :)

**Comment by mukrop** [comment]
:-}
