### ISSUE TITLE
Příliš dlouhé texty aktivit

### ISSUE THREAD

**Issue by malinajan** [zverinec/ks-muni-web#61]
Po integraci seznamu orgů začaly texty aktivit přetékat blok (pod fotkou je místo). Co s tím?
@mukrop

**Comment by mukrop** [comment]
Nakoniec som sa rozhodol este trochu skratit texty (200-250 znakov). Tj. ako model dlzky textu vezmime T-exkurzie. Znamena to, ze velke 4 bloky su OK, male 4 bloky potrebuju zmensit pismo (100%?) a mozno upravit margin/padding a 2 bloky chcu jemne upravit margin/padding.

**Comment by malinajan** [comment]
Upravil jsem na N-trophy. Další texty aktivit jsou ale stále dlouhé, viz např. KSI.

**Comment by mukrop** [comment]
KSI je u mna OK na velke 4 dlazdice a male 4 dlazdice. Nie je ok na 3 dlazide, ale je to asi 0.5mm (co by som riesil mensim paddingom o par pixlov). U teba sa zobrazuju nejake vyraznejsie problemy?

**Comment by malinajan** [comment]
U mě velké 4 dlaždice NOK. (změnšim trošku padding)

**Comment by malinajan** [comment]
Tak jsem si s tím pohrál, teď to snad vypadá dobře.

Projel jsem zběžně aktivity a skoro vše je dobré Až na jednu věc: když se zlomí pořadatelé na další řádek, všechno se rozbije. Text se zvětší a už se nevejde vedle fotky. Nechceme u těch akcí, kde je riziko zlomení, uvádět zkratky pořadatelů?

**Comment by malinajan** [comment]
(viz např. K-SCUK)

**Comment by mukrop** [comment]
Hm, vidim. Rozbija sa to ale az v sirke 3. Nechce sa mi uplne davat tam len skratky, pretoze KSI a IBIS ludom skoro nic nepovie (zatialco plny nazov ma vypovednu hodnotu). Davat rozne texty v uzkej a sirokej verzii je prilis zlozite a neudrzatelne... Uplne neviem, co s tym :-/.

Napad: Keby sme prerobili tu fotku tak, ze bude robit css cover na oblast, ktora je dana sirkou stlpca a vyskou bloku? Vo vseobecnosti to vzdy bude "skoro stvorec", pretoze ti presahy nie su velke (stale ma prioritu text vhodnej dlzky), ale je to robustnejsie riesenie (zachranuje nam situaciu ked zalomenim vzniknde +1 riadok). Co myslis? Je to trochu zvrhle, ale podla mna ta robustnost by za to mohla stat.
