### ISSUE TITLE
Doplnit fotky aktivit

### ISSUE THREAD

**Issue by malinajan** [zverinec/ks-muni-web#62]
@mukrop co s chybějícími fotkami aktivit? Máme ty fotky z archívů fakult? Kdo to udělá?

**Comment by mukrop** [comment]
V prvom rade si budu fotky akcie doplnat same. Az pre tie, ktore povedia, ze nic nemaki vyberieme nieco my (podla toho, co je to za akciu bud z nasho archivu alebo z archivu prirodovedy -- ten mam prislubeny). Takze toto sa bude riesit az neskor.
