### ISSUE TITLE
Vizual viac odkazujuci na MUNI

### ISSUE THREAD

**Issue by mukrop** [zverinec/ks-muni-web#63]
Poziadavka z UVT na domenu priamo pod muni.cz bola, ze z vizualu webu musi byt viac jasne, ze ide o projekt MUNI. Aktualne sa im to zda nedostatocne. Chceli loga fakult do paticky (uz pridane) a bud stitok do hlavicky alebo nejako inak zvyraznit, ze je to projekt MUNI. @AdelaRozari, skusis nieco vymysliet?

**Comment by malinajan** [comment]
Hotovo.
