### ISSUE TITLE
Přidat přesměrování ze starších webů

### ISSUE THREAD

**Issue by malinajan** [zverinec/ks-muni-web#66]
@mukrop Navhuji přesměrovat ks.muni.cz na prostredoskolaky.muni.cz. Kdo to umí zařídit?

Chceme přesměrovávat i ks.fi.muni.cz, nebo tu doménu prostě zrušíme se zrušením dev.ks.fi.muni.cz (asi během pár měsíců, po ukončení vývoje)?

**Comment by wormsik** [comment]
ks.fi.muni.cz je kdyztak hostovana na marsyasu, takze ji neni problem kamkoliv presmerovat...

**Comment by mukrop** [comment]
1) ks.muni.cz aktualne ukazuje na ganymeda, kde nic nie je (chvilu to na nasu ziadost ukazovalo na marsyas, ale pred nejakou dobou to zmenili bez toho aby to konzultovali s nami). Historicky to niekto pouzival, ale myslim si, ze uz dlhodobo nie (lebo tam dlhodobo skoro nic nie je).
2) ks.fi.muni.cz ukazuje na marsyas a je tam extra jednoduchy rozcestnik. Vzniklo to len preto, aby sa nam lahsie spravoval obsah na ks.muni.cz, ktory tam vtedy smeroval. O tejto adrese podla mna prakticky nikto nevie.
3) dev.ks.fi.muni.cz je len vyvojove.

Osobne navrhujem vsetky tri domeny zrusit (tj. napisat spravcom, ze sa moze zaznam zmazat a potom prejst tabulku zdrojov zverinca a odmazat to). Kvoli *.muni.cz sa pise na UVT Bohuslavovi Mouckovi, to mozem zariadit. A vzhladom na to, ze teraz ks.muni.cz ukazuje na ganymeda, asi by som to rovno nechal zrusit (a *.fi.muni.cz si Honza necha zrusit sam na CVT, ked uzna za vhodne). Co ty/vy na to?

**Comment by malinajan** [comment]
Ahoj, vzhledem k tomu, ze adresa ks.muni.cz se vyskytuje jako odkaz na nahodnych webech a starsich trickach KSI, byl bych spis pro udelat presmerovani na prostredoskolaky.muni.cz

**Comment by malinajan** [comment]
(Zbylé dvě zrušíme po dokončení vývoje.)

**Comment by mukrop** [comment]
OK, redirect zariadim.
