### ISSUE TITLE
V navigaci chybí záložka "Vše"

### ISSUE THREAD

**Issue by JanPokorny** [zverinec/ks-muni-web#69]
Současný způsob navigace je neintuitivní. Když vyberu třeba "Fyzika", tak pak není jasné, jak se zase vrátit na pohled, kde je všechno. (Opětovné kliknutí na "Fyzika" nic neudělá, musím dát v prohlížeči zpět nebo kliknout na logo.) Podle mě by bylo lepší mít tam záložku "Vše", jako první z těch co jsou na výběr.

Mockup:

![obrazek](https://user-images.githubusercontent.com/4580066/41739616-e80471c0-7595-11e8-82c5-d27103a78d00.png)

**Comment by malinajan** [comment]
Rozhodli jsme se to neřešit, klidně se s tebou pobavím o důvodech.
