### ISSUE TITLE
zveřejnit dlaždici o SOC na prostredoskolaky.muni.cz

### ISSUE THREAD

**Issue by AdelaRozari** [zverinec/ks-muni-web#70]
Uveřejnit dlaždici o SOC na prostredoskolaky.muni.cz a dát jí vždy navrch do "vlajkových" věcí.

**Comment by mukrop** [comment]
Toto je zase na mna.

**Comment by mukrop** [comment]
Dlazdica je nachystana (text, metadata, logo, fotka). Caka na stranky, potom sa moze zverejnit.

**Comment by AdelaRozari** [comment]
Stránka vypadá připravená. Kdyby šlo zveřejnit tu dlaždici :)

**Comment by mukrop** [comment]
Honza to urobi vecer. Inak ta stranka je vizualne dost hrozna, ja som navrhol Honzovi aspon nasledovne:

0) Prehodit "A co dal" ako prvu sekciu s nazvom "stredoskolska odborna cinnost". Linky prerobit na tlacitka (vid nizsie), zvazujem, ci su vsetky 3 nutne. Sockarov urcite nechat, druhy by som dal asi priamy link na ten zoznam tem, ak je to relevantne.
1) Kazdu druhu sekciu dat na biele pozadie (resp. na to, co je v blokoch na stranke aktivit). Farba cez cely sitku, tym padom nadradene blokove elementy, kludne medzi nimi trochu padding.
2) Text u FI prepisat na "Informace k SOC na Fakulte informatiky MU budou k dispozici od konce zazi 2018. Obecne dotazy ohledne psani SOC na fakulte vam odpovi Petr Kubicek."
3) Nadpisy je treba zmenit. Stredoskolaci nevedia, co je SCI, FI a ECON (obzvlast, kedze su to nove skratky).
4) Upravy obsahu:
SCI: Z odrazkoveho zoznamu na zaciatku by som mozno urobil 1 odstavec textu (nie som si isty, uvidime, ako to bude vyzerat). Medzinadpis info na ustavoch cely prec, Nazvy ustavov nechat tak, ako su.
ECON: Podnadpis zmenit na odstavcovy text.
5) Vsetky linky na weby pretobit na farebne tlacitka (tak ako vyzera tlacitko "prejit na web akce"), float a zarovnane vpravo (takze vlavo vacsinu sitky zaberie text, tlacitko bude vpravo). Tj. nemat linky zobrazene textom.
6) Vsetky mena, ktore su na stranke uvedene by mali byt preklik na mail alebo na MU verejnu stranku osoby. Tj. doplnit k veducim ECON a upravit kontaktne osoby za fakulty.
7) (optional) na ozivenie moze byt vedla nadpisu fakulty logo (ale asi je to teraz prilis vela stvania sa s tym).

**Comment by mukrop** [comment]
Mal som kus casu, tak som to dotiahol. Poslem Zuzke na korektury cestiny. Zatial to staci, potom si sasdneme a vyladime, co ma vlastne zmysel tam mat.
