### ISSUE TITLE
SAFARI stránka prostredoskolaky.muni.cz

### ISSUE THREAD

**Issue by AdelaRozari** [zverinec/ks-muni-web#73]
v prohlížeči safari náš web trochu blbne - dlaždice jsou jinak "vysoké". Na mobilu je to prý asi ok.

**Comment by mukrop** [comment]
Ma nizsiu prioritu ako SOCky (kedze su teraz sustredenia, bude to realne az v semestri).

**Comment by malinajan** [comment]
Děje se to pořád? Máte někdo počítač se Safari? Já ne...
