### ISSUE TITLE
Prediskutovat, co chceme na stranku o SOC

### ISSUE THREAD

**Issue by mukrop** [zverinec/ks-muni-web#74]
Meeting Martin + Adela + Honza + Zuzka.

**Comment by AdelaRozari** [comment]
Nejsem v Brníčku.

**Comment by mukrop** [comment]
V pohode, to ani ja (a Honza sice ano, ale za chvilu odide).
Niekedy v semestri, neponahla.

**Comment by mukrop** [comment]
Done.
