### ISSUE TITLE
Leták na web?

### ISSUE THREAD

**Issue by malinajan** [zverinec/ks-muni-web#76]
Dát odkaz na leták na web? Jen do textu jako link?

**Comment by mukrop** [comment]
Je dole v texte o akcich. To ti nestaci?

**Comment by malinajan** [comment]
Tam je jen brožura, ne? Leták tam nevidím.

**Comment by mukrop** [comment]
Aha, neuvedomil som si, ze myslis letak. Podla mna ho tam nedavajme, je to skoro identicke s titulkou brozury a pochybujem, ze by to niekto odtial tlacil na nastenku... Co myslis ty?

**Comment by AdelaRozari** [comment]
nedávala bych to tam. souhlasím s martinem.

**Comment by malinajan** [comment]
Ok.
