### ISSUE TITLE
V malém layoutu přidat margin vlevo a vpravo

### ISSUE THREAD

**Issue by malinajan** [zverinec/ks-muni-web#78]
(na mobilních zařízeních)

**Comment by malinajan** [comment]
Teď tam ten margin je; jeslti je třeba ještě zvětšit, dejte vědět.

**Comment by mukrop** [comment]
Hm, fakt? Ja asi nevidim ziadnu zmenu (alebo mi stale pride maly).
Plus drobnost: Ak by sa to dalo, bolo by mozne po rozkliku akcie na mobile mat medzi rozbalenym popisom a blokom s logom nulovy padding (tak ako popis temy SOC)? Na desktope to uplne zmysel nedava, ale na mobile je ta medzera medzi logom a popisom podla mna skor matuca.
