### ISSUE TITLE
Detailna analytika

### ISSUE THREAD

**Issue by mukrop** [zverinec/ks-muni-web#80]
Vedeli by sme zistovat statistiky, ktore aktivity ludia rozklikavaju? Samotne aktivity a PR oddelenia fakult by to podla mna zaujimalo. GA to podla mna nejako podporovat bude.

Navrhujem pogooglit, ak to bude super-komplikovane, tak nic, ale je netrivialna sanca, ze to nebude zlozite.

**Comment by mukrop** [comment]
Chceme, pisem report a presne tato informacia mi chyba.
https://support.google.com/analytics/answer/1136920?hl=en

That means, either add tracking code directly or integrate Google Tag Manager.

**Comment by mukrop** [comment]
@horacekj co s tymto? Je to trochu prace naviac, ale je to _presne_ to, co aktivity a fakulty podla mna budu chciet vediet. (A my to podla mna tiez budeme chciet vediet :-})

**Comment by malinajan** [comment]
Tohle jsem nikdy nedělal, musím prostudovat, jak to funguje. Během pár týdnů bych se k tomu měl dostat.

**Comment by malinajan** [comment]
Zkoušel jsem to nasadit a nefunglovalo :/.

**Comment by mukrop** [comment]
Pridas mi prosim pristup do Tag managera na prostredoskolaky.muni.cz?

Skusal si aj tu programatorsku verziu uvedenu na https://support.google.com/analytics/answer/1136920?hl=en (tj. pridanie eventu na kazdy a tag)?

**Comment by mukrop** [comment]
Rozchodil som to a.... je to magic :D.
Niekedy by sme sa mohli stretnut, ukazem ti to a naplanujeme, co by nas mohlo zaujimat trackovat (a ako to napasovat na existujuce premenne).

**Comment by mukrop** [comment]
Hotovo.
