### ISSUE TITLE
Zmenit stare skratky fakult na nove.

### ISSUE THREAD

**Issue by mukrop** [zverinec/ks-muni-web#82]
PřF MU -> SCI MUNI a pod.

**Comment by malinajan** [comment]
@AdelaRozari Prosím o návrh.

**Comment by mukrop** [comment]
Toto je zalezitost pre mna, treba to zmenit v datach (ustav, kt. to organizuje a pod.)

**Comment by mukrop** [comment]
Done. Export do gitu som nerobil (ano akce ani SOC),
