### ISSUE TITLE
Parsovat csv sloupce na základě ID sloupců

### ISSUE THREAD

**Issue by malinajan** [zverinec/ks-muni-web#83]
Doplnit unikátní ID sloupců

**Comment by mukrop** [comment]
Hm? Toto je poznamka pre teba, alebo nieco pre mna?
Aktivity unikatne ID maju a pokial viem, na SOC prace sme sa dohodli, ze ho nepotrebujes, pretoze nenesie ziadnu informaciu (vazna na fotky), takze si ho bdues generovat za behu. Alebo sa mylim?

**Comment by malinajan** [comment]
Tohle není pro tebe. Dívej se na to, komu je issue přiřazeno.

**Comment by mukrop** [comment]
Ved hej, ale to vedla, ktore som vyrabal ja tiez nie je pre Adelu, ktorej si to priradil :D.
