### ISSUE TITLE
Zviditelnit mail na vedoucího

### ISSUE THREAD

**Issue by Krejdom** [zverinec/ks-muni-web#87]
Pokud nemám nakonfigurovaného mailového klienta a nevím, že mail zjistím i pravým klikem, nejsem schopna zjistit mail na vedoucího.

**Rychlé řešení: přidat mail za jméno vedoucího**
Vedoucí práce: Ing. Vilém Pařil, Ph.D. --> Vedoucí práce: Ing. Vilém Pařil, Ph.D., vilem@mail.muni.cz

Otázkou zůstává, co s tím tlačíkem.

**Comment by malinajan** [comment]
Hotovo.
