### ISSUE TITLE
Nedelitelne medzery pred predlozky

### ISSUE THREAD

**Issue by mukrop** [zverinec/ks-muni-web#90]
Doplnit automaticke doplnovanie nedelitelnych medzier pred vybrane predlozky. Navrhujem regexp v ramci deploy kroku, ktory bude realizovat toto:
```
// Automatically replace spaces after prepositions with non-breakable spaces
$(document).ready(function(){
    var x = document.querySelector("body");
    x.innerHTML = x.innerHTML.replace(/ ([ai]|[kosuvz]|do|ke|na|od|po|se|ve|za|ze) /ig, " $1&nbsp;");
});
```

**Comment by malinajan** [comment]
Co to je na blbost? Nedělitelné mezery se dávají jen před jednopísmenné předložky.

**Comment by mukrop** [comment]
Nedelitelne medzery kvoli nezalamovaniu riadkov sa davaju za viacero veci, napriklad za skratky "tj." "tzv." (viz napr. http://prirucka.ujc.cas.cz/?id=880).
Mas pravdu, ze slabicne predlozky pokryvat nechceme.
