### ISSUE TITLE
Zvazit atribut pre SOCky, ze tema je obsadena

### ISSUE THREAD

**Issue by mukrop** [zverinec/ks-muni-web#91]
Tj. mat sltpec, kde za bude zadavat 0/1 alebo take nieco namiesto upravy nazvu temy.

**Comment by mukrop** [comment]
@horacekj Ked sa vratis z K-SCUKu a budes mat trochu casu, tak toto chcem prediskutovat.

**Comment by malinajan** [comment]
Prostě sloupec *Stav*, kde bude *volno* nebo *obsazeno*? Stavím se u tebe jak se vrátím z K-SCUKu.
