### ISSUE TITLE
Umožnit zobrazovat/skrývat ukončené SOČ

### ISSUE THREAD

**Issue by malinajan** [zverinec/ks-muni-web#94]
* Pravděpodobně nějaký JS.
*  Tlačítko zobrazit/skrýt kde? Dole na stránce?
* By default ukončené práce skrývat. Obsazené práce vždy zobrazovat.

**Comment by malinajan** [comment]
Ukončené SOČ se nezborazují vůbec (bez možnosti je zobrazit). Chceme ještě něco speciálního?

**Comment by mukrop** [comment]
Zatial to asi staci takto. Nie som si isty, ci zobrazovanie uzatvorenych bude mat nejaky zmysel (bude ich cim dalej tym viac). Ale v tabulke by som ich nechal, uvidime, ako sa to zase za rok vyvinie.

**Comment by malinajan** [comment]
Tak, je to konečně implementováno. Pro jednoduchost je to nakonec samostatná stránka. Přidal jsem navíc pár věcí, například aby se témata řadila. Nasazeno na produkční server. Vyhovuje nám to takto?

**Comment by mukrop** [comment]
* Samostatna stranka mi nevadi, akt o bolo jednoduhsie, preco nie.
* Zasednutie uzatvorenych temat je dobre.
* Vaham, ci "ukonceno" je spravny vyraz. "Obhajeno"? "Uzavreno"? "Jiz nevypisovano"? Co myslis?
* Nemenil by som pre samostatnu stranku tak vyrazne nadpis. Nechal by som asi "Stredoskolska odborna cinnost" a pridal len za to do zatvorky (mozno mensim a mozno do samostatneho riadku) nieco ako "(vsechna temata)".
* Tlacitko na zobrazenie vsetkych tem mi pride stylom velmi neintuitivne. Vyzera presne tak isto ako tie dve vedla (sockari, jcmm), ale funkcionalita je o dost ina (neodkazuje to prec, len to meni zobrazenie). Ako minimalnu zmenu by som videl aspon dat domu outline styl (mozes zobrat ten, co je hore na "zpet na vsechny akce"). Inak vaham aj nieco ine, v tej hlavicke si to podla mna malokto vsimne – mozno dokonca vedla nazvu kazdeho ustavu, ktory ma uzatvorene prace, ze by bolo nevyrazne outline tlacitko? (Funkcionalita jednej samostatnej stranky podla mna moze zostat.) Pride mi totiz, ze ked hladas SOC, pojdes po teme (geografia, informatika, ...) a odkaz v hlavicke po zascrollovani uz nenajdes. Co myslis?

**Comment by malinajan** [comment]
* Ohledně slova: moc nevím. Zkoušel jsem nad tím přemýšlet a žádné "nejlepší" mě z toho nevyšlo.
* Nadpis: ok, upraveno.
* Tlačíko: přidán outline styl a dáno na nový řádek. Já myslím, že když hledáš SOČ, stará témata tě moc nezajímají. "Zobrazit uzavřená témata" vnímám spíš jako "Archív SOČ" (možná je tohle dobré jméno pro stránku i tlačítko – "Zobrazit archív prací"? Ale asi evokuje, že by pod tímto odkazem nejsou aktuálně vypisovaná témata... Zkrátka: podle mě usecase archívu je spíš propagace a prezentace, nikoliv hledání tématu. Proto mi nevadí mít jedno tlačítko nahoře.

**Comment by mukrop** [comment]
* Slovo: OK, nechajme tak.
* Tlacitko: Super, dik.
* Nadpis: Hm, nejako sa mi tie dva nadpisy pod sebou nezdaju... Skus mozno ten druhy dat do zatvrotky, nieco ako "(zobrazena i ukončená témata)"?
* Ad pouzitie: Rozumiem tomu, co hovoris. Zuzka (PřF) zase vravela, ze myslienka je vidiet v ukoncenych temach, co dany ustav robi (aby sa student pripadne mohol ozvat, ze chce podobnu temu). Nechajme takto, poslem fakultam na vyjadrenie a uvidime.

Ale hlavne: Aktualne to tlacitko nefunguje :D. Resp. u mna sa po kliku sice zmeni nadpis, ale ziadne zatvorene temy nevidim (ale pred tym si pamatam, ze to fungovalo).

**Comment by malinajan** [comment]
Už funguje.
