### ISSUE TITLE
Otvarat emaily v novom okne

### ISSUE THREAD

**Issue by mukrop** [zverinec/ks-muni-web#97]
Emailove kontakty (na SOC stranke vedla mena veduceho a po kliku na tlacitko) by som otvaral v novom okne/tabe (tj. `target="_blank"`). Aktualne email nahradi stranku, co je trochu neprehladne (a nemozes v maile referencovat temu, na ktoru pises).

**Comment by malinajan** [comment]
U mně třeba ve Firefoxu žádná změna i když přidám `target=_blank`, ale je to tam.

**Comment by mukrop** [comment]
U mna zmena je (Chrome), otvara sa v novom tabe. Dik.
